// Generated by Scripts/generate-components.py. Edit the example files instead.
extension CNComponentGallery {
    var source: String {
        switch self {
        case .accordion:
            return ###"""
import SwiftUI
import SwiftCN

struct AccordionExample: View {
    @State private var expanded: Set<String> = []
    private let options = [CNOption("design", title: "Design system"), CNOption("mobile", title: "Mobile app"), CNOption("archive", title: "Archived", isDisabled: true)]

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            CNAccordion(options, expanded: $expanded, mode: .single) { option in
                Text("Native disclosure content for \(option.title). ").tw("text-sm text-mutedForeground")
            } label: { option in Text(option.title) }

        }
    }
}
"""### + "\n"
        case .alert:
            return ###"""
import SwiftUI
import SwiftCN

struct AlertExample: View {

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            CNAlert {
                Label("Changes saved", systemImage: "checkmark.circle").tw("alert-title")
                CNAlertDescription("Your workspace is up to date.")
            }

        }
    }
}
"""### + "\n"
        case .alert_dialog:
            return ###"""
import SwiftUI
import SwiftCN

struct AlertDialogExample: View {
    @State private var text = ""
    @State private var presented = false

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            CNAlertDialog("Delete workspace?", isPresented: $presented) {
                Button("Cancel", role: .cancel) {}
                Button("Delete", role: .destructive) { text = "Deleted" }
            } message: { Text("This action removes the workspace.") } label: { Text("Delete workspace") }

        }
    }
}
"""### + "\n"
        case .aspect_ratio:
            return ###"""
import SwiftUI
import SwiftCN

struct AspectRatioExample: View {

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            CNAspectRatio(16 / 9, classes: "bg-accent rounded-lg") {
                Image(systemName: "photo").tw("text-3xl text-mutedForeground")
            }.tw("w-full")

        }
    }
}
"""### + "\n"
        case .attachment:
            return ###"""
import SwiftUI
import SwiftCN

struct AttachmentExample: View {

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            CNAttachment(url: URL(string: "https://github.com/cbethin/swiftcn")!, title: "Design notes", detail: "Markdown · 12 KB")

        }
    }
}
"""### + "\n"
        case .avatar:
            return ###"""
import SwiftUI
import SwiftCN

struct AvatarExample: View {

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            HStack {
                CNAvatar(accessibilityLabel: "Charles Bethin") { Text("CB").tw("text-sm font-semibold") }
                CNAvatar(accessibilityLabel: "Team member", classes: "w-12 h-12") { Image(systemName: "person.fill") }
            }

        }
    }
}
"""### + "\n"
        case .badge:
            return ###"""
import SwiftUI
import SwiftCN

struct BadgeExample: View {

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            HStack {
                CNBadge("Released")
                CNBadge("Preview", classes: "bg-accent text-onAccent")
                CNBadge("Needs attention", classes: "bg-destructive text-onDestructive")
            }

        }
    }
}
"""### + "\n"
        case .breadcrumb:
            return ###"""
import SwiftUI
import SwiftCN

struct BreadcrumbExample: View {

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            CNBreadcrumb {
                Link("Home", destination: URL(string: "https://cbethin.github.io/swiftcn/")!)
                CNBreadcrumbSeparator()
                CNBreadcrumbPage("Components")
            }

        }
    }
}
"""### + "\n"
        case .bubble:
            return ###"""
import SwiftUI
import SwiftCN

struct BubbleExample: View {

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            VStack(alignment: .leading, spacing: 12) {
                CNBubble { Text("Can we keep this native?") }
                CNBubble("bg-primary text-onPrimary") { Text("Yes. Bindings and gestures stay in SwiftUI.") }
                    .frame(maxWidth: .infinity, alignment: .trailing)
            }

        }
    }
}
"""### + "\n"
        case .button:
            return ###"""
import SwiftUI
import SwiftCN

struct ButtonExample: View {
    @State private var count = 0

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            VStack(alignment: .leading, spacing: 8) {
                CNButton("Save changes", action: { count += 1 })
                CNButton("Preview", variant: .outline, action: {})
                CNButton("Delete", role: .destructive, variant: .destructive, action: {})
                Text("Saved \(count) times").tw("text-sm text-mutedForeground")
            }

        }
    }
}
"""### + "\n"
        case .button_group:
            return ###"""
import SwiftUI
import SwiftCN

struct ButtonGroupExample: View {

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            CNButtonGroup {
                CNButton("Previous", variant: .outline, action: {})
                CNButton("Next", variant: .outline, action: {})
                CNDropdownMenu("More") { CNDropdownMenuItem("Export") {} }
            }

        }
    }
}
"""### + "\n"
        case .calendar:
            return ###"""
import SwiftUI
import SwiftCN

struct CalendarExample: View {
    @State private var date = Date(timeIntervalSince1970: 1_760_054_400)

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            CNCalendar("Delivery date", selection: $date)

        }
    }
}
"""### + "\n"
        case .card:
            return ###"""
import SwiftUI
import SwiftCN

struct CardExample: View {
    @State private var text = "Design system"

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            CNCard {
                CNCardHeader { CNCardTitle("New workspace"); CNCardDescription("Keep your team in sync.") }
                CNCardContent { CNInput("Workspace name", text: $text) }
                CNCardFooter { CNButton("Create", action: {}) }
            }

        }
    }
}
"""### + "\n"
        case .carousel:
            return ###"""
import SwiftUI
import SwiftCN

struct CarouselExample: View {
    @State private var optionalSelection: String? = nil
    private let options = [CNOption("design", title: "Design system"), CNOption("mobile", title: "Mobile app"), CNOption("archive", title: "Archived", isDisabled: true)]

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            CNCarousel(options, selection: $optionalSelection, classes: "h-[160]") { option in
                CNCard {
                    CNCardHeader("pb-6") {
                        CNCardTitle { Text(option.title) }
                        CNCardDescription("Swipe or scroll to the next page.")
                    }
                }.tw("p-4")
            }

        }
    }
}
"""### + "\n"
        case .chart:
            return ###"""
import SwiftUI
import SwiftCN
import Charts

struct ChartExample: View {

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            CNChart("h-[200]") {
                ForEach(Array([12, 18, 14, 24].enumerated()), id: \.offset) { index, value in
                    BarMark(x: .value("Week", "Week \(index + 1)"), y: .value("Downloads", value), width: .ratio(0.55))
                }
            }.accessibilityLabel("Downloads by week")

        }
    }
}
"""### + "\n"
        case .checkbox:
            return ###"""
import SwiftUI
import SwiftCN

struct CheckboxExample: View {
    @State private var isOn = true

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            CNCheckbox("Accept the terms", isOn: $isOn)

        }
    }
}
"""### + "\n"
        case .collapsible:
            return ###"""
import SwiftUI
import SwiftCN

struct CollapsibleExample: View {
    @State private var isOn = true

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            CNCollapsible(isExpanded: $isOn) { Text("Details keep native disclosure behavior.").tw("text-sm") } label: { Text("Show details") }

        }
    }
}
"""### + "\n"
        case .combobox:
            return ###"""
import SwiftUI
import SwiftCN

struct ComboboxExample: View {
    @State private var optionalSelection: String? = nil
    private let options = [CNOption("design", title: "Design system"), CNOption("mobile", title: "Mobile app"), CNOption("archive", title: "Archived", isDisabled: true)]

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            CNCombobox("Choose a workspace", options: options, selection: $optionalSelection)

        }
    }
}
"""### + "\n"
        case .command:
            return ###"""
import SwiftUI
import SwiftCN

struct CommandExample: View {
    @State private var optionalSelection: String? = nil
    private let options = [CNOption("design", title: "Design system"), CNOption("mobile", title: "Mobile app"), CNOption("archive", title: "Archived", isDisabled: true)]

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            CNCommand(options, selection: $optionalSelection, classes: "h-[260]")

        }
    }
}
"""### + "\n"
        case .context_menu:
            return ###"""
import SwiftUI
import SwiftCN

struct ContextMenuExample: View {

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            CNContextMenu { Button("Duplicate") {}; Button("Delete", role: .destructive) {} } content: {
                CNCard("p-6") { Text("Right-click or long-press this card.") }
            }

        }
    }
}
"""### + "\n"
        case .data_table:
            return ###"""
import SwiftUI
import SwiftCN

struct DataTableExample: View {
    @State private var rowSelection: Set<String> = []
    @State private var sortOrder: [KeyPathComparator<CNOption<String>>] = []
    private let options = [CNOption("design", title: "Design system"), CNOption("mobile", title: "Mobile app"), CNOption("archive", title: "Archived", isDisabled: true)]

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            CNDataTable(options, selection: $rowSelection, sortOrder: $sortOrder, classes: "h-[220]") {
                TableColumn("Workspace", value: \.title)
                TableColumn("ID", value: \.id)
            }

        }
    }
}
"""### + "\n"
        case .date_picker:
            return ###"""
import SwiftUI
import SwiftCN

struct DatePickerExample: View {
    @State private var date = Date(timeIntervalSince1970: 1_760_054_400)

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            CNDatePicker("Delivery date", selection: $date)

        }
    }
}
"""### + "\n"
        case .dialog:
            return ###"""
import SwiftUI
import SwiftCN

struct DialogExample: View {
    @State private var text = "Design system"
    @State private var presented = false

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            CNDialog(isPresented: $presented) {
                CNDialogHeader { CNDialogTitle("Edit workspace"); CNDialogDescription("Update the native fields below.") }
                CNInput("Name", text: $text)
                CNDialogFooter { CNDialogClose(); CNButton("Save", action: { presented = false }) }
            } label: { Text("Edit workspace") }

        }
    }
}
"""### + "\n"
        case .direction:
            return ###"""
import SwiftUI
import SwiftCN

struct DirectionExample: View {

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            CNDirection(.rightToLeft) {
                HStack { Image(systemName: "arrow.forward"); Text("Direction follows the environment.") }.tw("p-4 bg-accent rounded-lg")
            }

        }
    }
}
"""### + "\n"
        case .drawer:
            return ###"""
import SwiftUI
import SwiftCN

struct DrawerExample: View {
    @State private var presented = false

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            CNDrawer(isPresented: $presented) {
                CNDialogTitle("Activity")
                Text("On iOS, drag between medium and large detents. macOS uses a native sheet.")
                CNDialogClose()
            } label: { Text("Show activity") }

        }
    }
}
"""### + "\n"
        case .dropdown_menu:
            return ###"""
import SwiftUI
import SwiftCN

struct DropdownMenuExample: View {
    var showsInlinePreview = false
    @State private var notifications = true
    @State private var lastAction = "No action selected"

    private var actions: some View {
        Group {
            CNDropdownMenuLabel("Workspace")
            CNDropdownMenuItem(action: { lastAction = "Rename selected" }) {
                Image(systemName: "pencil").tw("w-4")
                Text("Rename")
                Spacer()
                CNDropdownMenuShortcut("⌘R")
            }
            CNDropdownMenuItem(action: { lastAction = "Duplicate selected" }) {
                Image(systemName: "square.on.square").tw("w-4")
                Text("Duplicate")
            }
            CNDropdownMenuSeparator()
            CNDropdownMenuCheckboxItem(isOn: $notifications) { Text("Notifications") }
            CNDropdownMenuSeparator()
            CNDropdownMenuItem(role: .destructive, action: { lastAction = "Delete selected" }) {
                Image(systemName: "trash").tw("w-4")
                Text("Delete workspace")
            }
        }
    }
    var body: some View {
        VStack(alignment: .leading, spacing: 16) {
            CNDropdownMenu("Workspace actions") { actions }
            if showsInlinePreview {
                // Image captures show the parts without opening a second window.
                CNDropdownMenuContent("border max-w-[260]", autofocus: false) { actions }
            }
            Text(lastAction).tw("text-xs text-mutedForeground")
        }
    }
}
"""### + "\n"
        case .empty:
            return ###"""
import SwiftUI
import SwiftCN

struct EmptyExample: View {

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            CNEmpty {
                Image(systemName: "tray").tw("text-3xl").accessibilityHidden(true)
                CNEmptyTitle("No projects yet")
                CNEmptyDescription("Create your first project to get started.")
                CNEmptyContent { CNButton("Create project", action: {}) }
            }

        }
    }
}
"""### + "\n"
        case .field:
            return ###"""
import SwiftUI
import SwiftCN

struct FieldExample: View {
    @State private var text = "Design system"

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            CNField(isInvalid: text.isEmpty) {
                CNFieldLabel("Workspace name")
                CNInput("Name", text: $text)
                CNFieldDescription("A name your team will recognize.")
                if text.isEmpty { CNFieldError("Enter a workspace name.") }
            }

        }
    }
}
"""### + "\n"
        case .hover_card:
            return ###"""
import SwiftUI
import SwiftCN

struct HoverCardExample: View {

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            CNHoverCard {
                CNDialogTitle("swiftcn")
                CNDialogDescription("Composable styling for native SwiftUI.")
            } label: { Text("About swiftcn") }

        }
    }
}
"""### + "\n"
        case .input:
            return ###"""
import SwiftUI
import SwiftCN

struct InputExample: View {
    @State private var text = "Design system"

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            CNInput("Workspace name", text: $text)

        }
    }
}
"""### + "\n"
        case .input_group:
            return ###"""
import SwiftUI
import SwiftCN

struct InputGroupExample: View {
    @State private var text = "Design system"

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            CNInputGroup {
                CNInputGroupAddon { Image(systemName: "magnifyingglass").accessibilityHidden(true) }
                CNInputGroupField("Search projects", text: $text)
                CNButton("Search", variant: .ghost, size: .small, action: {})
            }

        }
    }
}
"""### + "\n"
        case .input_otp:
            return ###"""
import SwiftUI
import SwiftCN

struct InputOTPExample: View {
    @State private var code = ""

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            CNInputOTP(code: $code)

        }
    }
}
"""### + "\n"
        case .item:
            return ###"""
import SwiftUI
import SwiftCN

struct ItemExample: View {

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            CNItem {
                Image(systemName: "folder").accessibilityHidden(true)
                CNItemContent { CNItemTitle("Design system"); CNItemDescription("Shared native components") }
                Spacer()
                CNItemActions { CNButton("Open", variant: .outline, action: {}) }
            }

        }
    }
}
"""### + "\n"
        case .kbd:
            return ###"""
import SwiftUI
import SwiftCN

struct KbdExample: View {

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            HStack { Text("Search"); CNKbd("⌘ K") }

        }
    }
}
"""### + "\n"
        case .label:
            return ###"""
import SwiftUI
import SwiftCN

struct LabelExample: View {

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            CNLabel { Label("Notifications", systemImage: "bell") }

        }
    }
}
"""### + "\n"
        case .marker:
            return ###"""
import SwiftUI
import SwiftCN

struct MarkerExample: View {

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            VStack(alignment: .leading) {
                CNMarker(variant: .inline) { CNMarkerIcon { Image(systemName: "checkmark") }; Text("Changes saved") }
                CNMarker("Today", variant: .separator)
            }

        }
    }
}
"""### + "\n"
        case .menubar:
            return ###"""
import SwiftUI
import SwiftCN

struct MenubarExample: View {

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            CNMenubar {
                CNDropdownMenu("File") { CNDropdownMenuItem("New") {}; CNDropdownMenuItem("Open") {} }
                CNDropdownMenu("Edit") { CNDropdownMenuItem("Undo") {}; CNDropdownMenuItem("Redo") {} }
            }

        }
    }
}
"""### + "\n"
        case .message:
            return ###"""
import SwiftUI
import SwiftCN

struct MessageExample: View {

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            CNMessage {
                CNAvatar(accessibilityLabel: "Charles") { Text("CB") }
                CNMessageContent {
                    CNMessageMeta("Charles · Just now")
                    CNBubble { Text("The components are yours to edit.") }
                    CNMessageActions { CNButton("Reply", variant: .ghost, size: .small, action: {}) }
                }
            }

        }
    }
}
"""### + "\n"
        case .message_scroller:
            return ###"""
import SwiftUI
import SwiftCN

struct MessageScrollerExample: View {
    private let options = [CNOption("design", title: "Design system"), CNOption("mobile", title: "Mobile app"), CNOption("archive", title: "Archived", isDisabled: true)]

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            CNMessageScroller(options, classes: "h-[160]") { option in
                CNBubble { Text(option.title) }
            }

        }
    }
}
"""### + "\n"
        case .native_select:
            return ###"""
import SwiftUI
import SwiftCN

struct NativeSelectExample: View {
    @State private var selection = "design"
    private let options = [CNOption("design", title: "Design system"), CNOption("mobile", title: "Mobile app"), CNOption("archive", title: "Archived", isDisabled: true)]

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            CNNativeSelect("Workspace", options: options, selection: $selection)

        }
    }
}
"""### + "\n"
        case .navigation_menu:
            return ###"""
import SwiftUI
import SwiftCN

struct NavigationMenuExample: View {

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            CNNavigationMenu {
                Link("Documentation", destination: URL(string: "https://cbethin.github.io/swiftcn/docs/")!)
                CNDropdownMenu("Resources") { CNDropdownMenuLink("GitHub", destination: URL(string: "https://github.com/cbethin/swiftcn")!) }
            }

        }
    }
}
"""### + "\n"
        case .pagination:
            return ###"""
import SwiftUI
import SwiftCN

struct PaginationExample: View {
    @State private var page = 1

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            CNPagination(page: $page, pageCount: 20)

        }
    }
}
"""### + "\n"
        case .popover:
            return ###"""
import SwiftUI
import SwiftCN

struct PopoverExample: View {
    @State private var presented = false
    @State private var isOn = true

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            CNPopover(isPresented: $presented) {
                CNDialogTitle("Display settings")
                CNSwitch("Show notifications", isOn: $isOn)
            } label: { Text("Display settings") }

        }
    }
}
"""### + "\n"
        case .progress:
            return ###"""
import SwiftUI
import SwiftCN

struct ProgressExample: View {

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            CNProgress("Uploading", value: 0.65)

        }
    }
}
"""### + "\n"
        case .questionnaire:
            return ###"""
import SwiftUI
import SwiftCN

struct QuestionnaireExample: View {
    @State private var answers: [String: CNAnswer] = [:]
    @State private var questionIndex = 0
    @State private var submitted = false

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            CNQuestionnaire([
                CNQuestion("name", title: "What is your workspace called?"),
                CNQuestion("plan", title: "Choose a plan", kind: .single([
                    CNOption("personal", title: "Personal"), CNOption("team", title: "Team")
                ]))
            ], answers: $answers, activeIndex: $questionIndex) { _ in submitted = true }
            Text(submitted ? "Submitted" : "Answers stay in your app.").tw("text-sm text-mutedForeground")

        }
    }
}
"""### + "\n"
        case .radio_group:
            return ###"""
import SwiftUI
import SwiftCN

struct RadioGroupExample: View {
    @State private var selection = "design"
    private let options = [CNOption("design", title: "Design system"), CNOption("mobile", title: "Mobile app"), CNOption("archive", title: "Archived", isDisabled: true)]

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            CNRadioGroup("Workspace", options: options, selection: $selection)

        }
    }
}
"""### + "\n"
        case .resizable:
            return ###"""
import SwiftUI
import SwiftCN

struct ResizableExample: View {
    @State private var fraction = 0.35

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            CNResizable(fraction: $fraction, classes: "h-[160]") {
                Text("Sidebar").tw("p-4 w-full")
            } second: { Text("Editor").tw("p-4 w-full") }

        }
    }
}
"""### + "\n"
        case .scroll_area:
            return ###"""
import SwiftUI
import SwiftCN

struct ScrollAreaExample: View {

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            CNScrollArea(classes: "h-[150]") {
                VStack(alignment: .leading, spacing: 12) { ForEach(0..<20) { Text("Project \($0 + 1)") } }.tw("p-3")
            }

        }
    }
}
"""### + "\n"
        case .select:
            return ###"""
import SwiftUI
import SwiftCN

struct SelectExample: View {
    @State private var selection = "design"
    private let options = [CNOption("design", title: "Design system"), CNOption("mobile", title: "Mobile app"), CNOption("archive", title: "Archived", isDisabled: true)]

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            CNSelect("Workspace", options: options, selection: $selection)

        }
    }
}
"""### + "\n"
        case .separator:
            return ###"""
import SwiftUI
import SwiftCN

struct SeparatorExample: View {

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            VStack { Text("Workspace"); CNSeparator(); Text("Settings").tw("text-sm text-mutedForeground") }

        }
    }
}
"""### + "\n"
        case .sheet:
            return ###"""
import SwiftUI
import SwiftCN

struct SheetExample: View {
    @State private var presented = false
    @State private var isOn = true

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            CNSheet(isPresented: $presented) {
                CNDialogTitle("Workspace settings")
                CNSwitch("Notifications", isOn: $isOn)
                CNDialogClose()
            } label: { Text("Settings") }

        }
    }
}
"""### + "\n"
        case .sidebar:
            return ###"""
import SwiftUI
import SwiftCN

struct SidebarExample: View {
    @State private var optionalSelection: String? = nil
    @State private var visibility: NavigationSplitViewVisibility = .all
    private let options = [CNOption("design", title: "Design system"), CNOption("mobile", title: "Mobile app"), CNOption("archive", title: "Archived", isDisabled: true)]

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            CNSidebar(visibility: $visibility) {
                List(options, selection: $optionalSelection) { option in Text(option.title).tag(option.id) }
                    .navigationTitle("Workspaces")
            } detail: { Text(optionalSelection ?? "Choose a workspace") }.tw("h-[260]")

        }
    }
}
"""### + "\n"
        case .skeleton:
            return ###"""
import SwiftUI
import SwiftCN

struct SkeletonExample: View {

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            CNSkeleton(isLoading: true) {
                VStack(alignment: .leading, spacing: 6) { Text("A workspace title"); Text("Loading a thoughtful description.").tw("text-sm") }
            }

        }
    }
}
"""### + "\n"
        case .slider:
            return ###"""
import SwiftUI
import SwiftCN

struct SliderExample: View {
    @State private var volume = 0.65

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            CNSlider("Volume", value: $volume)

        }
    }
}
"""### + "\n"
        case .spinner:
            return ###"""
import SwiftUI
import SwiftCN

struct SpinnerExample: View {

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            CNSpinner("Loading workspace")

        }
    }
}
"""### + "\n"
        case .switch:
            return ###"""
import SwiftUI
import SwiftCN

struct SwitchExample: View {
    @State private var isOn = true

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            CNSwitch("Notifications", isOn: $isOn)

        }
    }
}
"""### + "\n"
        case .table:
            return ###"""
import SwiftUI
import SwiftCN

struct TableExample: View {

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            CNTable {
                CNTableRow { CNTableHead("Workspace"); CNTableHead("Status") }
                CNTableRow { CNTableCell("Design system"); CNTableCell { CNBadge("Ready") } }
                CNTableRow { CNTableCell("Mobile app"); CNTableCell("In progress") }
            }

        }
    }
}
"""### + "\n"
        case .tabs:
            return ###"""
import SwiftUI
import SwiftCN

struct TabsExample: View {
    @State private var tab = 0

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            CNTabs(selection: $tab, classes: "h-[180]") {
                Text("Account settings").tw("p-4").tabItem { Label("Account", systemImage: "person") }.tag(0)
                Text("Security settings").tw("p-4").tabItem { Label("Security", systemImage: "lock") }.tag(1)
            }

        }
    }
}
"""### + "\n"
        case .textarea:
            return ###"""
import SwiftUI
import SwiftCN

struct TextareaExample: View {
    @State private var text = "Design system"

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            CNTextarea("Project description", text: $text, classes: "h-[120]")

        }
    }
}
"""### + "\n"
        case .toast:
            return ###"""
import SwiftUI
import SwiftCN

struct ToastExample: View {
    @State private var toast: CNToast? = nil

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            CNToastHost(toast: $toast) {
                CNButton("Save changes", action: { toast = CNToast(title: "Saved", message: "Your changes are up to date.") })
                    .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .topLeading)
            }.tw("h-[180]")

        }
    }
}
"""### + "\n"
        case .toggle:
            return ###"""
import SwiftUI
import SwiftCN

struct ToggleExample: View {
    @State private var isOn = true

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            CNToggle(isOn: $isOn) { Label("Bold", systemImage: "bold") }

        }
    }
}
"""### + "\n"
        case .toggle_group:
            return ###"""
import SwiftUI
import SwiftCN

struct ToggleGroupExample: View {
    @State private var rowSelection: Set<String> = []
    private let options = [CNOption("design", title: "Design system"), CNOption("mobile", title: "Mobile app"), CNOption("archive", title: "Archived", isDisabled: true)]

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            CNToggleGroup(options, selection: $rowSelection)

        }
    }
}
"""### + "\n"
        case .tooltip:
            return ###"""
import SwiftUI
import SwiftCN

struct TooltipExample: View {

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            CNTooltip("Download the workspace") {
                Label("Download", systemImage: "arrow.down.to.line").tw("text-sm")
            }

        }
    }
}
"""### + "\n"
        case .typography:
            return ###"""
import SwiftUI
import SwiftCN

struct TypographyExample: View {

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            VStack(alignment: .leading, spacing: 8) {
                CNTypography("Native by design", style: .title)
                CNTypography("A shared styling language for SwiftUI.", style: .lead)
                CNTypography("Keep your content, bindings, and gestures native.")
                CNTypography("import SwiftCN", style: .code)
            }

        }
    }
}
"""### + "\n"
        }
    }
}
