// Generated by Scripts/generate-components.py. Edit the native example files instead.
extension CNNativeComposition {
    var source: String {
        switch self {
        case .styles:
            return ###"""
import SwiftUI
import SwiftCN

struct NativeStylesExample: View {
    private enum Field: Hashable { case amount }
    @State private var amount = 12.5
    @State private var notifications = true
    @State private var disabled = false
    @State private var compact = false
    @State private var horizontal = false
    @State private var saves = 0
    @FocusState private var focusedField: Field?

    var body: some View {
        VStack(alignment: .leading, spacing: 16) {
            CNField(spacing: 12, axis: horizontal ? .horizontal : .vertical) {
                Label("Amount", systemImage: "number")
                    .labelStyle(.tw("field-label", base: .titleAndIcon))
                VStack(alignment: .leading, spacing: 6) {
                    TextField("Amount", value: $amount, format: .number)
                        .textFieldStyle(.tw("input", state: .init(isFocused: focusedField == .amount)))
                        .focused($focusedField, equals: .amount)
                        .onSubmit(save)
                        .disabled(disabled)
                    CNFieldDescription("Formatting, selection, and submit handling stay native.")
                }
            }.tw("feedback-motion", value: horizontal)
            Toggle("Notifications", isOn: $notifications)
                .toggleStyle(.tw("switch", base: .switch))
                .disabled(disabled)
            CNButtonGroup {
                Button("Save", action: save)
                    .buttonStyle(.tw("button-primary"))
                    .keyboardShortcut("s", modifiers: .command)
                Button("Edit amount") { focusedField = .amount }
                    .buttonStyle(.tw("button-outline"))
            }.disabled(disabled)
            Text("Saved \(saves) times · Amount: \(amount.formatted(.number))")
                .tw("text-sm text-mutedForeground")
            CNCheckbox("Disable controls", isOn: $disabled)
            CNCheckbox("Compact input recipe", isOn: $compact)
            CNCheckbox("Label beside the input", isOn: $horizontal)
        }
        .twRules {
            if compact {
                $0.named["input"] = "px-3 py-1 min-h-[44] border rounded-lg bg-surface focus:border-primary disabled:opacity-45"
            }
        }
    }
    private func save() { saves += 1; focusedField = nil }
}
"""### + "\n"
        case .drawer:
            return ###"""
import SwiftUI
import SwiftCN

struct NativeDrawerExample: View {
    @State private var nativeOpen = false
    @State private var convenienceOpen = false
    @State private var detent = PresentationDetent.height(260)
    @State private var preventDismissal = false
    @State private var dismissals = 0
    @Environment(\.twTheme) private var theme
    @Environment(\.colorScheme) private var scheme

    var body: some View {
        VStack(alignment: .leading, spacing: 16) {
            Button("Open caller-owned sheet") { nativeOpen = true }
                .buttonStyle(.tw("button-outline"))
                .sheet(isPresented: $nativeOpen, onDismiss: didDismiss) {
                    ScrollView {
                        CNDrawerContent {
                            CNDialogTitle("Activity")
                            Text("The content uses a recipe. This sheet owns its configuration.")
                                .tw("text-sm text-mutedForeground")
                            Toggle("Prevent swipe dismissal", isOn: $preventDismissal)
                                .toggleStyle(.tw("switch", base: .switch))
                            Button("Expand") { withAnimation { detent = .large } }
                                .buttonStyle(.tw("button-secondary"))
                            Button("Done") { nativeOpen = false }
                                .buttonStyle(.tw("button-outline"))
                        }
                    }
                    .presentationDetents([.height(260), .large], selection: $detent)
                    .presentationDragIndicator(.visible)
                    .interactiveDismissDisabled(preventDismissal)
                    .presentationBackground(theme.color(.surface, scheme: scheme))
                    .preferredColorScheme(scheme)
                    #if os(macOS)
                        .frame(minWidth: 360, minHeight: 320)
                    #endif
                }
            CNDrawer(isPresented: $convenienceOpen, detents: [.height(260), .large],
                     selection: $detent, onDismiss: didDismiss) {
                CNDialogTitle("Convenience drawer")
                Text("The same content part, with native scrolling and presentation defaults.")
                    .tw("text-sm text-mutedForeground")
                Button("Expand") { withAnimation { detent = .large } }
                    .buttonStyle(.tw("button-secondary"))
                CNDialogClose()
            } label: { Text("Open convenience drawer") }
            Text("Dismissed \(dismissals) times").tw("text-sm text-mutedForeground")
        }
    }
    private func didDismiss() { dismissals += 1 }
}
"""### + "\n"
        case .surfaces:
            return ###"""
import SwiftUI
import SwiftCN

struct NativeSurfacesExample: View {
    private enum Tool: String, CaseIterable { case pencil, highlighter, eraser }
    @State private var appearance = TWAppearance.automatic
    @State private var tool = Tool.pencil
    @State private var expanded = false
    @State private var shares = 0
    @State private var sheetOpen = false
    @State private var note = ""
    @Namespace private var surfaces

    var body: some View {
        VStack(alignment: .leading, spacing: 16) {
            Picker("Appearance", selection: $appearance) {
                Text("Automatic").tag(TWAppearance.automatic)
                Text("Glass").tag(TWAppearance.glass)
                Text("Solid").tag(TWAppearance.solid)
            }.pickerStyle(.segmented)
            HStack(spacing: 12) {
                Button("Share") { shares += 1 }
                    .buttonStyle(.twNative("glass px-1"))
                Button("Open note") { sheetOpen = true }
                    .buttonStyle(.twNative("glass-prominent px-2 font-semibold"))
            }
            TWSurfaceGroup(spacing: 12) {
                HStack(spacing: 12) {
                    HStack(spacing: 4) {
                        ForEach(Tool.allCases, id: \.self) { item in
                            Button { tool = item } label: {
                                Image(systemName: item.rawValue).tw("p-2")
                                    .foregroundStyle(tool == item ? Color.accentColor : .primary)
                            }
                            .buttonStyle(.plain)
                            .accessibilityLabel(item.rawValue.capitalized)
                            .accessibilityAddTraits(tool == item ? .isSelected : [])
                        }
                        Button { withAnimation(.smooth) { expanded.toggle() } } label: {
                            Image(systemName: expanded ? "chevron.left" : "ellipsis").tw("p-2")
                        }
                        .buttonStyle(.plain)
                        .accessibilityLabel(expanded ? "Fewer tools" : "More tools")
                    }
                    .tw("px-2 py-1 surface-floating glass-interactive")
                    .twSurfaceID("tools", in: surfaces)
                    if expanded {
                        Button { tool = .pencil } label: { Image(systemName: "arrow.uturn.backward").tw("p-2") }
                            .buttonStyle(.plain)
                            .accessibilityLabel("Reset tool")
                            .tw("p-1 surface-floating glass-interactive")
                            .twSurfaceID("reset", in: surfaces)
                    }
                }
            }
            .tw("p-6 rounded-lg")
            .background(LinearGradient(colors: [.orange, .pink, .indigo], startPoint: .topLeading, endPoint: .bottomTrailing),
                        in: .rect(cornerRadius: 12))
            Text("Tool: \(tool.rawValue) · Shared \(shares) times").tw("text-sm text-mutedForeground")
        }
        .twAppearance(appearance)
        .sheet(isPresented: $sheetOpen) {
            ScrollView {
                CNDrawerContent {
                    CNDialogTitle("Note")
                    TextField("Write a note", text: $note)
                        .textFieldStyle(.tw("input"))
                    Button("Done") { sheetOpen = false }
                        .buttonStyle(.twNative("glass-prominent"))
                }
            }
            .presentationDetents([.medium, .large])
            .presentationDragIndicator(.visible)
            .twPresentationSurface()
            .twAppearance(appearance)
            #if os(macOS)
                .frame(minWidth: 360, minHeight: 280)
            #endif
        }
    }
}
"""### + "\n"
        case .navigation:
            return ###"""
import SwiftUI
import SwiftCN

struct NativeNavigationExample: View {
    private enum Destination: String, CaseIterable, Identifiable {
        case inbox = "Inbox", projects = "Projects", archive = "Archive"
        var id: Self { self }
    }
    @State private var selected: Destination? = .projects
    @State private var visibility: NavigationSplitViewVisibility = .all
    @State private var draft = "A draft stays in caller-owned state."

    var body: some View {
        NavigationSplitView(columnVisibility: $visibility) {
            List(Destination.allCases, selection: $selected) { destination in
                NavigationLink(value: destination) {
                    Label(destination.rawValue, systemImage: "folder")
                        .labelStyle(.tw("sidebar-item-label"))
                }
            }
            .listStyle(.sidebar)
            .scrollContentBackground(.hidden)
            .tw("sidebar-list")
            .navigationSplitViewColumnWidth(min: 180, ideal: 220, max: .infinity)
            .navigationTitle("Workspace")
        } detail: {
            VStack(alignment: .leading, spacing: 16) {
                Text(selected?.rawValue ?? "Choose a destination").tw("text-xl font-semibold")
                CNFieldControl("textarea") {
                    TextEditor(text: $draft).scrollContentBackground(.hidden)
                        .accessibilityLabel("Project draft")
                }
                Text("SwiftUI owns column visibility, row selection, and compact navigation.")
                    .tw("text-sm text-mutedForeground")
            }
            .tw("p-6 bg-background")
            .navigationSplitViewColumnWidth(min: 300, ideal: 560, max: .infinity)
            .navigationTitle(selected?.rawValue ?? "Workspace")
        }
    }
}
"""### + "\n"
        case .split:
            return ###"""
import SwiftUI
import SwiftCN

struct NativeSplitExample: View {
    @State private var fraction = 0.4
    @State private var draft = "Resize the panes while keeping this draft."
    @State private var monospaced = false

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            #if os(macOS)
            HSplitView {
                inspector.tw("min-w-[160] w-full bg-surface")
                editor.tw("min-w-[220] w-full bg-surface")
            }.tw("border rounded-lg")
            #else
            CNResizable(fraction: $fraction, axis: .vertical, minimumFraction: 0.35) { inspector } second: { editor }
                .tw("border rounded-lg")
            #endif
            Text("Native desktop dividers; an explicit fraction and touch handle on mobile.")
                .tw("text-sm text-mutedForeground")
        }.frame(height: 420)
    }
    private var inspector: some View {
        VStack(alignment: .leading, spacing: 12) {
            Text("Inspector").tw("text-lg font-semibold")
            Toggle("Monospaced font", isOn: $monospaced).toggleStyle(.tw("switch", base: .switch))
            Spacer()
        }.frame(maxWidth: .infinity, alignment: .leading).tw("p-4")
    }
    private var editor: some View {
        VStack(alignment: .leading, spacing: 12) {
            Text("Editor").tw("text-lg font-semibold")
            TextEditor(text: $draft).scrollContentBackground(.hidden)
                .font(monospaced ? .system(.body, design: .monospaced) : .body)
                .accessibilityLabel("Split editor draft")
        }.frame(maxWidth: .infinity, alignment: .leading).tw("p-4")
    }
}
"""### + "\n"
        case .arrangement:
            return ###"""
import SwiftUI
import SwiftCN

/// Use this as a screen root. Keep navigation outside the native arrangement.
struct NativeArrangementExample: View {
    @State private var draft = "Edit this draft, then fold or resize the window."
    @State private var monospaced = false

    var body: some View {
        NavigationStack {
            GeometryReader { geometry in
                #if canImport(SwiftUI, _version: 8.0.85.27)
                if #available(iOS 27.1, macOS 27.1, *) {
                    ArrangementView {
                        editor
                    } secondary: {
                        inspector
                    }.arrangementViewStyle(.split)
                } else {
                    fallback(width: geometry.size.width)
                }
                #else
                fallback(width: geometry.size.width)
                #endif
            }.navigationTitle("Workspace")
        }
    }
    private func fallback(width: CGFloat) -> some View {
        let layout = width >= 640 ? AnyLayout(HStackLayout(spacing: 0)) : AnyLayout(VStackLayout(spacing: 0))
        return layout {
            editor
            inspector
        }
    }
    private var editor: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 12) {
                Text("Draft").tw("text-lg font-semibold")
                TextEditor(text: $draft)
                    .scrollContentBackground(.hidden)
                    .font(monospaced ? .system(.body, design: .monospaced) : .body)
                    .accessibilityLabel("Arrangement draft")
                    .tw("min-h-[240] p-3 border rounded-lg bg-surface")
            }.tw("p-6 w-full")
        }.scrollBounceBehavior(.basedOnSize).tw("w-full h-full bg-background")
    }
    private var inspector: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 16) {
                Text("Inspector").tw("text-lg font-semibold")
                Toggle("Monospaced font", isOn: $monospaced).toggleStyle(.tw("switch", base: .switch))
                Text("SwiftUI places these panes around active folds. The editor state belongs to this screen.")
                    .tw("text-sm text-mutedForeground")
            }.tw("p-6 w-full")
        }.tw("w-full h-full bg-surface")
    }
}
"""### + "\n"
        case .models:
            return ###"""
import SwiftUI
import Observation
import SwiftCN

@MainActor @Observable final class WorkspaceFormModel {
    var name = "Studio"
    var notifications = true
    var category: String? = "team"
    var query = ""
    var toasts: [CNToast] = []
    var savedName = ""
    var canSave: Bool { !name.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty }
    func save() {
        guard canSave else { return }
        savedName = name
        toasts.append(CNToast(title: "Workspace saved", message: name))
    }
}

struct NativeModelExample: View {
    @State private var model = WorkspaceFormModel()
    var body: some View { WorkspaceForm(model: model) }
}

private struct WorkspaceForm: View {
    @Bindable var model: WorkspaceFormModel
    @FocusState private var nameFocused: Bool
    private let categories = [CNOption("personal", title: "Personal", systemImage: "person"),
                              CNOption("team", title: "Team", systemImage: "person.2")]
    var body: some View {
        CNToastHost(toasts: $model.toasts) {
            VStack(alignment: .leading, spacing: 16) {
                CNField {
                    CNFieldLabel("Workspace name")
                    TextField("Name", text: $model.name)
                        .textFieldStyle(.tw("input", state: .init(isFocused: nameFocused)))
                        .focused($nameFocused).onSubmit(model.save)
                }
                Toggle("Notifications", isOn: $model.notifications).toggleStyle(.tw("switch", base: .switch))
                CNCommand(categories, selection: $model.category, query: $model.query, classes: "h-[180]")
                    .itemContent { option, selected in
                        HStack {
                            Label(option.title, systemImage: option.systemImage ?? "folder")
                            Spacer()
                            if selected { CNBadge("Selected") }
                        }
                    } empty: {
                        Label("No categories match your search.", systemImage: "magnifyingglass")
                            .tw("p-4 text-sm text-mutedForeground")
                    }
                Button("Save", action: model.save).buttonStyle(.tw("button-primary")).disabled(!model.canSave)
                Text(model.savedName.isEmpty ? "No saved changes" : "Saved: \(model.savedName)")
                    .tw("text-sm text-mutedForeground")
            }.frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .topLeading)
        }
        .toastContent { context in
            VStack(alignment: .leading, spacing: 8) {
                Text(context.toast.title).tw("text-sm font-semibold")
                if let message = context.toast.message { Text(message).tw("text-sm text-mutedForeground") }
                context.action("Edit name") { nameFocused = true; context.dismiss() }
            }
        }
        .frame(minHeight: 460)
    }
}
"""### + "\n"
        }
    }
}
