// Generated by Scripts/generate-components.py. Edit the native example files instead.
extension CNNativeComposition {
    var source: String {
        switch self {
        case .styles:
            return ###"""
import SwiftUI
import SwiftCN

struct NativeStylesExample: View {
    private enum Field: Hashable { case amount }
    @State private var amount = 12.5
    @State private var notifications = true
    @State private var disabled = false
    @State private var compact = false
    @State private var saves = 0
    @FocusState private var focusedField: Field?

    var body: some View {
        VStack(alignment: .leading, spacing: 16) {
            CNField {
                Label("Amount", systemImage: "number")
                    .labelStyle(.tw("field-label", base: .titleAndIcon))
                TextField("Amount", value: $amount, format: .number)
                    .textFieldStyle(.tw("input", state: .init(isFocused: focusedField == .amount)))
                    .focused($focusedField, equals: .amount)
                    .onSubmit(save)
                    .disabled(disabled)
                CNFieldDescription("Formatting, selection, and submit handling stay native.")
            }
            Toggle("Notifications", isOn: $notifications)
                .toggleStyle(.tw("switch", base: .switch))
                .disabled(disabled)
            CNButtonGroup {
                Button("Save", action: save)
                    .buttonStyle(.tw("button-primary"))
                    .keyboardShortcut("s", modifiers: .command)
                Button("Edit amount") { focusedField = .amount }
                    .buttonStyle(.tw("button-outline"))
            }.disabled(disabled)
            Text("Saved \(saves) times · Amount: \(amount.formatted(.number))")
                .tw("text-sm text-mutedForeground")
            CNCheckbox("Disable controls", isOn: $disabled)
            CNCheckbox("Compact input recipe", isOn: $compact)
        }
        .twRules {
            if compact {
                $0.named["input"] = "px-3 py-1 min-h-[44] border rounded-lg bg-surface focus:border-primary disabled:opacity-45"
            }
        }
    }
    private func save() { saves += 1; focusedField = nil }
}
"""### + "\n"
        case .drawer:
            return ###"""
import SwiftUI
import SwiftCN

struct NativeDrawerExample: View {
    @State private var nativeOpen = false
    @State private var convenienceOpen = false
    @State private var detent = PresentationDetent.height(260)
    @State private var preventDismissal = false
    @State private var dismissals = 0
    @Environment(\.twTheme) private var theme
    @Environment(\.colorScheme) private var scheme

    var body: some View {
        VStack(alignment: .leading, spacing: 16) {
            Button("Open caller-owned sheet") { nativeOpen = true }
                .buttonStyle(.tw("button-outline"))
                .sheet(isPresented: $nativeOpen, onDismiss: didDismiss) {
                    ScrollView {
                        CNDrawerContent {
                            CNDialogTitle("Activity")
                            Text("The content uses a recipe. This sheet owns its configuration.")
                                .tw("text-sm text-mutedForeground")
                            Toggle("Prevent swipe dismissal", isOn: $preventDismissal)
                                .toggleStyle(.tw("switch", base: .switch))
                            Button("Expand") { withAnimation { detent = .large } }
                                .buttonStyle(.tw("button-secondary"))
                            Button("Done") { nativeOpen = false }
                                .buttonStyle(.tw("button-outline"))
                        }
                    }
                    .presentationDetents([.height(260), .large], selection: $detent)
                    .presentationDragIndicator(.visible)
                    .interactiveDismissDisabled(preventDismissal)
                    .presentationBackground(theme.color(.surface, scheme: scheme))
                    .preferredColorScheme(scheme)
                    #if os(macOS)
                        .frame(minWidth: 360, minHeight: 320)
                    #endif
                }
            CNDrawer(isPresented: $convenienceOpen, detents: [.height(260), .large],
                     selection: $detent, onDismiss: didDismiss) {
                CNDialogTitle("Convenience drawer")
                Text("The same content part, with native scrolling and presentation defaults.")
                    .tw("text-sm text-mutedForeground")
                Button("Expand") { withAnimation { detent = .large } }
                    .buttonStyle(.tw("button-secondary"))
                CNDialogClose()
            } label: { Text("Open convenience drawer") }
            Text("Dismissed \(dismissals) times").tw("text-sm text-mutedForeground")
        }
    }
    private func didDismiss() { dismissals += 1 }
}
"""### + "\n"
        case .navigation:
            return ###"""
import SwiftUI
import SwiftCN

struct NativeNavigationExample: View {
    private enum Destination: String, CaseIterable, Identifiable {
        case inbox = "Inbox", projects = "Projects", archive = "Archive"
        var id: Self { self }
    }
    @State private var selected: Destination? = .projects
    @State private var visibility: NavigationSplitViewVisibility = .all
    @State private var draft = "A draft stays in caller-owned state."

    var body: some View {
        NavigationSplitView(columnVisibility: $visibility) {
            List(Destination.allCases, selection: $selected) { destination in
                NavigationLink(value: destination) {
                    Label(destination.rawValue, systemImage: "folder")
                        .labelStyle(.tw("sidebar-item-label"))
                }
            }
            .listStyle(.sidebar)
            .scrollContentBackground(.hidden)
            .tw("sidebar-list")
            .navigationTitle("Workspace")
        } detail: {
            VStack(alignment: .leading, spacing: 16) {
                Text(selected?.rawValue ?? "Choose a destination").tw("text-xl font-semibold")
                CNFieldControl("textarea") {
                    TextEditor(text: $draft).scrollContentBackground(.hidden)
                        .accessibilityLabel("Project draft")
                }
                Text("SwiftUI owns column visibility, row selection, and compact navigation.")
                    .tw("text-sm text-mutedForeground")
            }
            .tw("p-6 bg-background")
            .navigationTitle(selected?.rawValue ?? "Workspace")
        }
    }
}
"""### + "\n"
        case .split:
            return ###"""
import SwiftUI
import SwiftCN

struct NativeSplitExample: View {
    @State private var fraction = 0.35
    @State private var draft = "Resize the panes while keeping this draft."
    @State private var monospaced = false

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            #if os(macOS)
            HSplitView {
                inspector.tw("min-w-[160] bg-surface")
                editor.tw("min-w-[220] bg-surface")
            }.tw("border rounded-lg")
            #else
            CNResizable(fraction: $fraction) { inspector } second: { editor }
                .tw("border rounded-lg")
            #endif
            Text("Native desktop dividers; an explicit fraction and touch handle on mobile.")
                .tw("text-sm text-mutedForeground")
        }.frame(height: 320)
    }
    private var inspector: some View {
        VStack(alignment: .leading, spacing: 12) {
            Text("Inspector").tw("text-lg font-semibold")
            Toggle("Monospaced font", isOn: $monospaced).toggleStyle(.tw("switch", base: .switch))
            Spacer()
        }.tw("p-4")
    }
    private var editor: some View {
        VStack(alignment: .leading, spacing: 12) {
            Text("Editor").tw("text-lg font-semibold")
            TextEditor(text: $draft).scrollContentBackground(.hidden)
                .font(monospaced ? .system(.body, design: .monospaced) : .body)
                .accessibilityLabel("Split editor draft")
        }.tw("p-4")
    }
}
"""### + "\n"
        }
    }
}
