#!/usr/bin/env python3
"""Generate docs and licensed source assets from the catalog and actual Swift files."""
import argparse, io, json, sys, zipfile
from pathlib import Path

repo = Path(__file__).resolve().parents[1]
check = argparse.ArgumentParser()
check.add_argument('--check', action='store_true')
args = check.parse_args()
catalog = json.loads((repo / 'Components/catalog.json').read_text())
native_examples = json.loads((repo / 'Components/native-examples.json').read_text())
assert len(catalog) == 64 and len({c['slug'] for c in catalog}) == 64
outputs = {}
gallery_sources = ['// Generated by Scripts/generate-components.py. Edit the example files instead.\n',
                   'extension CNComponentGallery {\n    var source: String {\n        switch self {\n']
def put(path, content):
    outputs[repo / path] = content.encode() if isinstance(content, str) else content

for item in catalog:
    name, slug, filename = item['name'], item['slug'], item['source']
    source = (repo / 'Sources/SwiftCN' / filename).read_text()
    assert ('struct ' + item['symbol']) in source, f"Missing public component: {item['symbol']}"
    consumer_source = source.replace('import SwiftUI\n', 'import SwiftUI\nimport SwiftCN\n', 1)
    example = (repo / 'Examples/Components/Sources' / item['example']).read_text()
    assert '"""###' not in example and '\\###(' not in example
    gallery_sources.append(f'        case .{slug.replace("-", "_")}:\n            return ###"""\n{example.rstrip()}\n"""### + "\\n"\n')
    platform = 'iOS' if slug == 'tabs' else 'macOS'
    for appearance in ['light', 'dark']:
        if platform == 'iOS':
            reference = repo / 'Tests/SwiftCNVisualTests/__Snapshots__/components-ios-18.5-iphone-16' / f'ios.component-{slug}-{appearance}-standard.png'
        else:
            reference = repo / 'Tests/SwiftCNVisualTests/__Snapshots__/components-macos-15-xcode-16.4' / f'component.{slug.replace("-", "_")}-{appearance}-720-standard.png'
        put(f'website/public/native/components/{slug}-{appearance}.png', reference.read_bytes())
    put('website/public/registry/' + filename, consumer_source)
    put('website/public/registry/examples/' + item['example'], example)
    native_links = {
        'button': 'styles', 'input': 'styles', 'switch': 'styles', 'field': 'styles',
        'drawer': 'drawer', 'sidebar': 'navigation', 'resizable': 'split',
    }
    native_note = ''
    if slug in native_links:
        native_note = f'\n## Compose with native SwiftUI\n\nSee [complete native composition examples](/docs/native-composition#{native_links[slug]}) for direct native controls, caller-owned sheets, navigation, and desktop split views. The examples use the same editable recipes.\n'
    mdx = f'''---
title: {name}
description: Native {name.lower()} composition, package imports, and editable Swift source.
---

{{/* Generated by Scripts/generate-components.py. Edit the Swift source or catalog instead. */}}

## Preview

<NativeCapture name="components/{slug}" alt="{name} rendered by native SwiftUI." platform="{platform}" />

## Use it

Import `SwiftCN` to use `{item['symbol']}` directly. This complete example also runs in the native component gallery.

```swift title="{item['example']}"
{example.rstrip()}
```

## Native behavior

{item['notes']}{native_note}

## Style and compose

Visual recipes use `.tw` classes. Append `classes:` to override a recipe locally, or change the recipe in `TWGlobalRules.named` for your subtree. Native layout and interaction modifiers remain SwiftUI APIs. For control colors, append `cn-tint-[primary]`, another theme token, or an interpolated `Color`.

Motion recipes are editable too: `control-motion` uses a 150 ms smooth response, `disclosure-motion` uses a 250 ms spring, and `feedback-motion` uses a 200 ms smooth response. Set a recipe to `animate-none` in your global rules to turn it off. Presets respect Reduce Motion. Static components stay still; native scrolling, drag tracking, and platform presentation keep their own gestures.

Action groups and card, dialog, and questionnaire footers stack when their content does not fit. The native layout preserves the same child controls during this change.

View builders preserve native child content. Native Button roles, labels, keyboard shortcuts, submit actions, and presentation modifiers still work. A string recipe does not replace a native control API or a typed chart mark.

## Own the source

Copy the complete file below into your app alongside `import SwiftCN`. The file contains related composable parts from the same family. Its dependencies use public package APIs, so copied and imported components can coexist.

To own the styling engine too, download the complete source bundle. It contains every component, the `.tw` engine, its recipes, and the MIT license. Keep those files in one module and remove `import SwiftCN` from the usage example.

<ComponentSourceLinks source="{filename}" example="{item['example']}" />

```swift title="{filename}"
{consumer_source.rstrip()}
```
'''
    put('website/content/docs/component-library/' + slug + '.mdx', mdx)

gallery_sources.append('        }\n    }\n}\n')
put('Examples/Components/Sources/ComponentSource.swift', ''.join(gallery_sources))

native_sources = ['// Generated by Scripts/generate-components.py. Edit the native example files instead.\n',
                  'extension CNNativeComposition {\n    var source: String {\n        switch self {\n']
native_page = '''---
title: Native composition
description: Style native SwiftUI controls, sheets, navigation, and split views with editable recipes.
---

Use SwiftUI to own interaction and state. Use swiftcn to supply appearance and composable content parts.
These complete examples run in the gallery's **Native composition** section and compile with package imports or copied source.

Bindings, format styles, focus, navigation, and dismissal remain typed Swift APIs. Classes describe appearance and supported motion.
All paths share `TWGlobalRules.named`, `TWTheme`, and the existing `.tw` engine.

'''
for item in native_examples:
    example = (repo / 'Examples/Components/Sources' / item['example']).read_text()
    native_sources.append(f'        case .{item["slug"]}:\n            return ###"""\n{example.rstrip()}\n"""### + "\\n"\n')
    put('website/public/registry/examples/' + item['example'], example)
    native_page += f'''<a id="{item['slug']}" />

## {item['title']}

{item['notes']}

```swift title="{item['example']}"
{example.rstrip()}
```

<ComponentSourceLinks example="{item['example']}" />

'''
native_page += '''## Shared rules

Override a recipe for a subtree. Imported components and direct native adapters resolve the same rule:

```swift
.twRules {
    $0.named["input"] = "px-3 py-2 min-h-[44] border rounded-lg bg-surface focus:border-primary"
}
```

Use native `.disabled`, `.focused`, `.onSubmit`, and presentation modifiers for behavior. Supply style state for focus appearance.
The controls keep their native identity while recipes change.
'''
native_sources.append('        }\n    }\n}\n')
put('Examples/Components/Sources/NativeCompositionSource.swift', ''.join(native_sources))
put('website/content/docs/native-composition.mdx', native_page)

put('website/content/docs/component-library/meta.json', json.dumps({'title': 'Component library', 'pages': ['index'] + [c['slug'] for c in catalog]}, indent=2)+'\n')
index='''---
title: Native component library
description: All 64 catalog entries, with native behavior, runnable examples, and copyable source.
---

Every component is available from `import SwiftCN`. Each page has a complete usage example, native behavior notes, and the actual editable source. The native gallery runs those same examples:

```bash
swift run SwiftCNComponentGallery
```

Each gallery screen shows the complete example, including `import SwiftCN`, with a copy button. Run it on an iPhone simulator:

```bash
python3 Scripts/run-ios-component-gallery.py
```

Open `swiftcn-component-gallery` in Xcode Device Hub or Simulator after launch. The script uses a dedicated simulator.

Styling lives in `.tw` recipes. Custom SwiftUI surfaces compose native layout, buttons, bindings, focus, and accessibility. The dropdown uses a styled popover, and the calendar uses a styled month grid. These components adapt the [shadcn catalog](https://ui.shadcn.com/docs/components) to SwiftUI.

<ComponentSourceLinks />

| Component | Native API |
| --- | --- |
'''
for c in catalog:index+=f"| [{c['name']}](./{c['slug']}) | `{c['symbol']}` |\n"
put('website/content/docs/component-library/index.mdx', index)
put('website/public/registry/catalog.json', json.dumps(catalog,indent=2)+'\n')
put('website/public/registry/LICENSE', (repo/'LICENSE').read_text())
archive=io.BytesIO()
with zipfile.ZipFile(archive,'w',compression=zipfile.ZIP_DEFLATED) as bundle:
    files={f'SwiftCN/{p.name}':p.read_bytes() for p in sorted((repo/'Sources/SwiftCN').glob('*.swift'))}
    files.update({f'Examples/{c["example"]}':(repo/'Examples/Components/Sources'/c['example']).read_bytes() for c in catalog})
    files.update({f'Examples/{c["example"]}':(repo/'Examples/Components/Sources'/c['example']).read_bytes() for c in native_examples})
    files['LICENSE']=(repo/'LICENSE').read_bytes()
    files['README.md']=b'Add the SwiftCN folder to your app target. No runtime packages are required. Examples import SwiftCN; remove that import when the source lives in your app module. Requires iOS 17 or macOS 14. Keep LICENSE when redistributing.\n'
    for name,data in sorted(files.items()):
        info=zipfile.ZipInfo(name,date_time=(1980,1,1,0,0,0));info.compress_type=zipfile.ZIP_DEFLATED;info.external_attr=0o644<<16
        bundle.writestr(info,data)
put('website/public/registry/swiftcn-sources.zip',archive.getvalue())
changed=[]
for path, data in outputs.items():
    if not path.exists() or path.read_bytes()!=data:
        changed.append(str(path.relative_to(repo)))
        if not args.check:path.parent.mkdir(parents=True,exist_ok=True);path.write_bytes(data)
if args.check and changed:
    raise SystemExit('Stale generated component files:\n'+'\n'.join(changed))
print(f'{"Verified" if args.check else "Generated"} {len(catalog)} component pages and their source assets.')
